const data = [
    { id: "1", invited: 'Familia Martínez Canales', tickets: '2' },
    { id: "2", invited: 'Familia Escobedo Martínez', tickets: '7' },
    { id: "3", invited: 'Maria Esther Canales Guerrero', tickets: '2' },
    { id: "4", invited: 'Ibrain Miguel Gonzáles Canales', tickets: '2' },
    { id: "5", invited: 'Familia Flores Gonzáles', tickets: '4' },
    { id: "6", invited: 'Familia Canales Zavala', tickets: '3' },
    { id: "7", invited: 'Belen Canales Guerrero', tickets: '1' },
    { id: "8", invited: 'Saúl Canales Guerrero', tickets: '2' },
    { id: "9", invited: 'Elia García', tickets: '2' },
    { id: "10", invited: 'Ernesto López García', tickets: '2' },
    { id: "11", invited: 'Miguel Martínez', tickets: '1' },
    { id: "12", invited: 'Joel Sánchez', tickets: '2' },
    { id: "13", invited: 'Cayetano Moises Guerro Márquez', tickets: '2' },
    { id: "14", invited: 'Benjamín Torres Martínez', tickets: '2' },
    { id: "15", invited: 'Josías Sánchez Sánchez', tickets: '4' },
    { id: "16", invited: 'Asael Álvarez', tickets: '2' },
    { id: "17", invited: 'Alma Sosa', tickets: '2' },
    { id: "18", invited: 'Gamaliel Astivia', tickets: '1' },
    { id: "19", invited: 'Isra Sánchez Esparza', tickets: '2' },
    { id: "20", invited: 'Ismael Valdéz Alonso', tickets: '1' },
    { id: "21", invited: 'Andrea Ibarra', tickets: '1' },
    { id: "22", invited: 'Familia Olivares Maldonado', tickets: '3' },
    { id: "23", invited: 'Familia Martínez Olivares', tickets: '3' },
    { id: "24", invited: 'Familia Chávez Olguín', tickets: '5' },
    { id: "25", invited: 'Familia Olivares Gutiérrez', tickets: '2' },
    { id: "26", invited: 'Familia Tellez Chávez', tickets: '2' },
    { id: "27", invited: 'Roberto Chávez', tickets: '3' },
    { id: "28", invited: 'Familia Díaz Chávez', tickets: '2' },
    { id: "29", invited: 'Familia Chávez Contreras', tickets: '2' },
    { id: "30", invited: 'Familia Mendieta Chávez', tickets: '3' },
    { id: "31", invited: 'Pedro Maldonado', tickets: '2' },
    { id: "32", invited: 'Verónica Maldonado', tickets: '1' },
    { id: "33", invited: 'Beatríz Maldonado', tickets: '1' },
    { id: "34", invited: 'Familia Antolin Arce', tickets: '3' },
    { id: "35", invited: 'Familia Antolin Álvarez', tickets: '2' },
    { id: "36", invited: 'Familia Maldonado Casarreal', tickets: '5' },
    { id: "37", invited: 'Familia Gutiérrez López', tickets: '2' },
    { id: "38", invited: 'Angelica Maldonado', tickets: '1' },
    { id: "39", invited: 'Rosalva Salazar', tickets: '1' },
    { id: "40", invited: 'Ángeles Vidal', tickets: '2' },
    { id: "41", invited: 'Alfredo y Karen', tickets: '2' },
    { id: "42", invited: 'Familia Martínez Esquivel', tickets: '2' },
    { id: "43", invited: 'Eduardo Chávez', tickets: '2' },
    { id: "44", invited: 'Familia Pita de la Rosa', tickets: '4' },
    { id: "45", invited: 'Rubí y Rocío', tickets: '2' },
    { id: "46", invited: 'Ricardo Maldonado García', tickets: '3' },
    { id: "47", invited: 'Familia Hernández Rodríguez', tickets: '2' },
    { id: "48", invited: 'Daniela Huitrón', tickets: '1' },
    { id: "49", invited: 'Abraham González', tickets: '2' },
    { id: "50", invited: 'Familia Rodríguez Villa', tickets: '2' },
    { id: "51", invited: 'Familia Rodríguez Escoto', tickets: '2' },
    { id: "52", invited: 'Pablo Muñoz', tickets: '1' },
    { id: "53", invited: 'Familia Maldonado García', tickets: '1' },
    { id: "54", invited: 'Ruth Navarrete', tickets: '1' },
    { id: "55", invited: 'Mitzi Acevedo', tickets: '1' },
    { id: "56", invited: 'Familia González Aguilar', tickets: '3' },
    { id: "57", invited: 'Familia Ortega Hernández', tickets: '2' },
    { id: "58", invited: 'Familia Silva Ramos', tickets: '4' },
    { id: "59", invited: 'Familia Guarneros López', tickets: '2' },
    { id: "60", invited: 'Adareli Guarneros López', tickets: '1' },
    { id: "61", invited: 'Iraiz & Oto', tickets: '2' },
    { id: "62", invited: 'Familia Sánchez Moreno', tickets: '2' },
    { id: "63", invited: 'Familia Maldonado', tickets: '4' },
    { id: "64", invited: 'Ángel del Ángel', tickets: '1' },
    { id: "65", invited: 'Familia Cruz Hernández', tickets: '6' },
    { id: "66", invited: 'Familia Pineda Domínguez', tickets: '4' },
    { id: "67", invited: 'Familia Ramírez Pineda', tickets: '4' },
    { id: "68", invited: 'Familia Gutiérrez Hernández', tickets: '2' },
    { id: "69", invited: 'Familia Hernández Gutiérrez', tickets: '4' },
    { id: "70", invited: 'Familia Benítez Gutiérrez', tickets: '3' },
    { id: "71", invited: 'Silvia Vázquez Mancilla', tickets: '1' },
    { id: "72", invited: 'Juanita', tickets: '1' },
    { id: "73", invited: 'Angeles Guzmán', tickets: '2' },
    { id: "74", invited: 'Margarita & Fabiola', tickets: '2' },
    { id: "75", invited: 'Omar Corona', tickets: '1' },
    { id: "76", invited: 'Herson David Vázquez', tickets: '2' },
    { id: "77", invited: 'Surisadai Bazaldual', tickets: '2' },
    { id: "78", invited: 'Monica Mercado', tickets: '2' },
    { id: "79", invited: 'Familia Mejía Orta', tickets: '2' },
    { id: "80", invited: 'Nohemi Aguilar', tickets: '2' },
    { id: "81", invited: 'Marifer Cano', tickets: '2' },
    { id: "82", invited: 'David Felix', tickets: '2' },
    { id: "83", invited: 'Lourdes Constantino', tickets: '1' },
    { id: "84", invited: 'Familia Conde Lozano', tickets: '2' },
    { id: "85", invited: 'Roberto Serratos', tickets: '2' },
    { id: "86", invited: 'Moisés Serratos', tickets: '4' },
    { id: "87", invited: 'Anette Olvera', tickets: '3' },
    { id: "88", invited: 'Elio Hernández', tickets: '2' },
    { id: "89", invited: 'David Cuevas', tickets: '2' },
    { id: "90", invited: 'Familia Jiménez Martínez', tickets: '4' },
    { id: "91", invited: 'Zoé Sánchez', tickets: '2' },
];

export default data;